name: CI - Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        perl: [ '5.34', '5.36' ]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6

    - name: Set up Perl
      if: matrix.os != 'windows-latest'
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Set up Perl (Windows optimized)
      if: matrix.os == 'windows-latest'
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
        windows-job-type: 'strawberry-perl'

    - name: Cache CPAN modules
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cpanm
          C:\Users\runneradmin\.cpanm  # Windows
          ${{ github.workspace }}/local
        key: ${{ runner.os }}-cpan-${{ hashFiles('**/cpanfile', '**/META.yml', '**/META.json') }}
        restore-keys: |
          ${{ runner.os }}-cpan-

    - name: Install dependencies
      env:
        PERL_MM_USE_DEFAULT: 1
        PERL_EXTUTILS_AUTOINSTALL: --defaultdeps
      run: |
        cpanm --quiet --notest --installdeps --with-develop .

    - name: Run tests
      run: |
        prove -l t/

    - name: Perl Critic
      run: |
        perlcritic --quiet bin/fix-mp3-tags lib/

    - name: Check formatting (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        find bin lib -name '*.pl' -o -name '*.pm' | xargs -n1 perltidy --check

    - name: Check formatting (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -Path bin,lib -Include *.pl,*.pm | ForEach-Object {
          perltidy --check $_.FullName
        }
